// <auto-generated />
using LicoreriaSistema.Datos.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LicoreriaSistema.Datos.Migrations
{
    [DbContext(typeof(LicoreriaDbContext))]
    [Migration("20260913174733_AlcanceGlobalUsuario")]
    partial class AlcanceGlobalUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LicoreriaSistema.Dominio.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("LicoreriaSistema.Dominio.Entidades.InventarioSucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("StockMaximo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StockMinimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.HasIndex("ProductoId", "SucursalId")
                        .IsUnique();

                    b.ToTable("InventariosSucursal");
                });

            modelBuilder.Entity("LicoreriaSistema.Dominio.Entidades.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Codigo = "PRODUCTOS_CONSULTAR",
                            Descripcion = "Permite consultar productos y precios.",
                            Nombre = "Consultar productos"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Codigo = "INVENTARIO_CONSULTAR",
                            Descripcion = "Permite consultar existencias.",
                            Nombre = "Consultar inventario"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Codigo = "VENTAS_CONSULTAR",
                            Descripcion = "Permite consultar ventas e historial.",
                            Nombre = "Consultar ventas"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Codigo = "CLIENTES_CONSULTAR",
                            Descripcion = "Permite consultar clientes registrados.",
                            Nombre = "Consultar clientes"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Codigo = "PRODUCTOS_GESTIONAR",
                            Descripcion = "Crear, modificar y administrar productos.",
                            Nombre = "Gestionar productos"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Codigo = "CATEGORIAS_GESTIONAR",
                            Descripcion = "Crear, modificar y administrar categorías.",
                            Nombre = "Gestionar categorías"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Codigo = "INVENTARIO_ENTRADA",
                            Descripcion = "Permite registrar entradas de mercancía.",
                            Nombre = "Registrar entradas de inventario"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Codigo = "INVENTARIO_SALIDA",
                            Descripcion = "Permite registrar salidas de mercancía.",
                            Nombre = "Registrar salidas de inventario"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Codigo = "INVENTARIO_AJUSTAR",
                            Descripcion = "Permite realizar ajustes de inventario.",
                            Nombre = "Ajustar inventario"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Codigo = "TRANSFERENCIAS_CREAR",
                            Descripcion = "Permite crear transferencias entre sucursales.",
                            Nombre = "Crear transferencias"
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Codigo = "TRANSFERENCIAS_AUTORIZAR",
                            Descripcion = "Permite autorizar transferencias.",
                            Nombre = "Autorizar transferencias"
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            Codigo = "TRANSFERENCIAS_ENVIAR",
                            Descripcion = "Permite ejecutar el envío de mercancía.",
                            Nombre = "Enviar transferencias"
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            Codigo = "TRANSFERENCIAS_RECIBIR",
                            Descripcion = "Permite confirmar la recepción de mercancía.",
                            Nombre = "Recibir transferencias"
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            Codigo = "VENTAS_CREAR",
                            Descripcion = "Permite registrar ventas.",
                            Nombre = "Crear ventas"
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            Codigo = "VENTAS_ANULAR",
                            Descripcion = "Permite anular ventas según las reglas de autorización.",
                            Nombre = "Anular ventas"
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            Codigo = "CLIENTES_CREAR",
                            Descripcion = "Permite registrar clientes durante la operación.",
                            Nombre = "Registrar clientes"
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            Codigo = "CLIENTES_EDITAR",
                            Descripcion = "Permite modificar datos de clientes.",
                            Nombre = "Editar clientes"
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            Codigo = "CAJA_OPERAR",
                            Descripcion = "Permite realizar operaciones de caja y cobro.",
                            Nombre = "Operar caja"
                        },
                        new
                        {
                            Id = 19,
                            Activo = true,
                            Codigo = "CAJA_CIERRE",
                            Descripcion = "Permite realizar el cierre de caja propio.",
                            Nombre = "Realizar cierre de caja"
                        },
                        new
                        {
                            Id = 20,
                            Activo = true,
                            Codigo = "USUARIOS_CONSULTAR",
                            Descripcion = "Permite consultar usuarios.",
                            Nombre = "Consultar usuarios"
                        },
                        new
                        {
                            Id = 21,
                            Activo = true,
                            Codigo = "USUARIOS_GESTIONAR",
                            Descripcion = "Permite crear, modificar y administrar usuarios dentro del alcance permitido.",
                            Nombre = "Gestionar usuarios"
                        },
                        new
                        {
                            Id = 22,
                            Activo = true,
                            Codigo = "SUCURSALES_CONSULTAR",
                            Descripcion = "Permite consultar sucursales.",
                            Nombre = "Consultar sucursales"
                        },
                        new
                        {
                            Id = 23,
                            Activo = true,
                            Codigo = "SUCURSALES_GESTIONAR",
                            Descripcion = "Permite crear y modificar sucursales según las reglas del sistema.",
                            Nombre = "Gestionar sucursales"
                        },
                        new
                        {
                            Id = 24,
                            Activo = true,
                            Codigo = "REPORTES_CONSULTAR",
                            Descripcion = "Permite consultar reportes según el alcance del usuario.",
                            Nombre = "Consultar reportes"
                        },
                        new
                        {
                            Id = 25,
                            Activo = true,
                            Codigo = "CONFIGURACION_GESTIONAR",
                            Descripcion = "Permite administrar la configuración general del negocio.",
                            Nombre = "Gestionar configuración"
                        },
                        new
                        {
                            Id = 26,
                            Activo = true,
                            Codigo = "ROLES_GESTIONAR",
                            Descripcion = "Permite administrar roles y sus permisos.",
                            Nombre = "Gestionar roles"
                        },
                        new
                        {
                            Id = 27,
                            Activo = true,
                            Codigo = "PERMISOS_GESTIONAR",
                            Descripcion = "Permite administrar los permisos del sistema.",
                            Nombre = "Gestionar permisos"
                        },
                        new
                        {
                            Id = 28,
                            Activo = true,
                            Codigo = "CODIGO_ROTATIVO_CONFIGURAR",
                            Descripcion = "Permite configurar el umbral del código rotativo.",
                            Nombre = "Configurar código rotativo"
                        },
                        new
                        {
                            Id = 29,
                            Activo = true,
                            Codigo = "CODIGO_ROTATIVO_AUTORIZAR",
                            Descripcion = "Permite autorizar operaciones que requieran código rotativo.",
                            Nombre = "Autorizar con código rotativo"
                        });
                });

            modelBuilder.Entity("LicoreriaSistema.Dominio.Entidades.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PrecioCompra")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("LicoreriaSistema.Dominio.Entidades.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Control total del sistema y del negocio.",
                            Nombre = "SuperAdministrador"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Administración del negocio dentro de su alcance.",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Supervisión operativa de una sucursal.",
                            Nombre = "Encargado de Sucursal"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Ventas, cobros y atención al cliente.",
                            Nombre = "Vendedor/Cajero"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Gestión y control del inventario.",
                            Nombre = "Almacén/Inventario"
                        });
                });

            modelBuilder.Entity("LicoreriaSistema.Dominio.Entidades.RolPermiso", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("PermisoId")
                        .HasColumnType("int");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("RolPermisos");

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            PermisoId = 1
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 2
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 3
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 4
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 5
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 6
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 7
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 8
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 9
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 10
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 11
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 12
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 13
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 14
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 15
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 16
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 17
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 18
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 19
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 20
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 21
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 22
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 23
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 24
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 25
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 26
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 27
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 28
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 29
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 1
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 2
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 3
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 4
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 5
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 6
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 7
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 8
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 9
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 10
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 11
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 12
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 13
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 14
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 15
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 16
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 17
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 20
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 21
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 22
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 24
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 1
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 2
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 3
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 4
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 11
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 13
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 15
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 17
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 20
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 22
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 24
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 29
                        },
                        new
                        {
                            RolId = 4,
                            PermisoId = 1
                        },
                        new
                        {
                            RolId = 4,
                            PermisoId = 3
                        },
                        new
                        {
                            RolId = 4,
                            PermisoId = 4
                        },
                        new
                        {
                            RolId = 4,
                            PermisoId = 14
                        },
                        new
                        {
                            RolId = 4,
                            PermisoId = 16
                        },
                        new
                        {
                            RolId = 4,
                            PermisoId = 17
                        },
                        new
                        {
                            RolId = 4,
                            PermisoId = 18
                        },
                        new
                        {
                            RolId = 4,
                            PermisoId = 19
                        },
                        new
                        {
                            RolId = 5,
                            PermisoId = 1
                        },
                        new
                        {
                            RolId = 5,
                            PermisoId = 2
                        },
                        new
                        {
                            RolId = 5,
                            PermisoId = 3
                        },
                        new
                        {
                            RolId = 5,
                            PermisoId = 7
                        },
                        new
                        {
                            RolId = 5,
                            PermisoId = 8
                        },
                        new
                        {
                            RolId = 5,
                            PermisoId = 9
                        },
                        new
                        {
                            RolId = 5,
                            PermisoId = 10
                        },
                        new
                        {
                            RolId = 5,
                            PermisoId = 12
                        },
                        new
                        {
                            RolId = 5,
                            PermisoId = 13
                        },
                        new
                        {
                            RolId = 5,
                            PermisoId = 22
                        },
                        new
                        {
                            RolId = 5,
                            PermisoId = 24
                        });
                });

            modelBuilder.Entity("LicoreriaSistema.Dominio.Entidades.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("LicoreriaSistema.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("AlcanceGlobal")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasFilter("[Correo] IS NOT NULL");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LicoreriaSistema.Dominio.Entidades.UsuarioSucursal", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "SucursalId");

                    b.HasIndex("SucursalId");

                    b.ToTable("UsuariosSucursales");
                });

            modelBuilder.Entity("LicoreriaSistema.Dominio.Entidades.InventarioSucursal", b =>
                {
                    b.HasOne("LicoreriaSistema.Dominio.Entidades.Producto", "Producto")
                        .WithMany("Inventarios")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LicoreriaSistema.Dominio.Entidades.Sucursal", "Sucursal")
                        .WithMany("Inventarios")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("LicoreriaSistema.Dominio.Entidades.Producto", b =>
                {
                    b.HasOne("LicoreriaSistema.Dominio.Entidades.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("LicoreriaSistema.Dominio.Entidades.RolPermiso", b =>
                {
                    b.HasOne("LicoreriaSistema.Dominio.Entidades.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LicoreriaSistema.Dominio.Entidades.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("LicoreriaSistema.Dominio.Entidades.Usuario", b =>
                {
                    b.HasOne("LicoreriaSistema.Dominio.Entidades.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("LicoreriaSistema.Dominio.Entidades.UsuarioSucursal", b =>
                {
                    b.HasOne("LicoreriaSistema.Dominio.Entidades.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LicoreriaSistema.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("UsuarioSucursales")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LicoreriaSistema.Dominio.Entidades.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("LicoreriaSistema.Dominio.Entidades.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("LicoreriaSistema.Dominio.Entidades.Producto", b =>
                {
                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("LicoreriaSistema.Dominio.Entidades.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("LicoreriaSistema.Dominio.Entidades.Sucursal", b =>
                {
                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("LicoreriaSistema.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("UsuarioSucursales");
                });
#pragma warning restore 612, 618
        }
    }
}
